// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input v8824f2,
 input vclk,
 output v41c924,
 output v980ce1,
 output v5ad277,
 output v9c8ff5,
 output v755ffa,
 output [0:7] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign w1 = v8824f2;
 assign v980ce1 = w2;
 assign v5ad277 = w3;
 assign v755ffa = w4;
 assign v9c8ff5 = w5;
 assign v41c924 = w8;
 assign w8 = v8824f2;
 assign w9 = vclk;
 assign w10 = vclk;
 assign w11 = vclk;
 assign w8 = w1;
 assign w10 = w9;
 assign w11 = w9;
 assign w11 = w10;
 v3bfe20 vead016 (
  .v3c12b5(w0),
  .ve7f5e6(w1),
  .v717e81(w9)
 );
 v8e2728 v492da1 (
  .v10eedb(w0),
  .v2dffca(w6),
  .v0884a0(w10)
 );
 vf4ae9c v1889d4 (
  .ve0793c(w2),
  .v86c7f4(w3),
  .v7c09bb(w4),
  .v8a6138(w5),
  .vd1c1a8(w6),
  .vec8411(w7),
  .vfc0c62(w11)
 );
 v21cfcc va16e59 (
  .v9fb85f(w7)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v3bfe20 (
 input v717e81,
 input ve7f5e6,
 output v3c12b5
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = ve7f5e6;
 assign w1 = v717e81;
 assign v3c12b5 = w2;
 v3bfe20_v683a9f v683a9f (
  .i(w0),
  .clk(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Sync  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sincronizar las entradas de datos con el reloj del sistema
/*-------------------------------------------------*/

module v3bfe20_v683a9f (
 input clk,
 input i,
 output o
);
 // Sincronizacion. Evitar 
 // problema de la metaestabilidad
 
 reg d1;
 reg d2;
 
 always @(posedge clk)
  d1 <= i;
  
 always @(posedge clk)
   d2 <= d1;
   
 assign o = d2;
endmodule
//---- Top entity
module v8e2728 (
 input v0884a0,
 input v10eedb,
 output v2dffca
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v10eedb;
 assign v2dffca = w1;
 assign w2 = v0884a0;
 v8e2728_v115ffb v115ffb (
  .i(w0),
  .o(w1),
  .clk(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Subida  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Detector de flanco de subida. Emite un tic cuando detecta un flanco ascendente
/*-------------------------------------------------*/

module v8e2728_v115ffb (
 input clk,
 input i,
 output o
);
 reg q = 0;
 
 always @(posedge clk)
   q <= i;
   
 assign o = (~q & i);  
endmodule
//---- Top entity
module vf4ae9c (
 input vd1c1a8,
 input vec8411,
 input vfc0c62,
 output ve0793c,
 output v86c7f4,
 output v8a6138,
 output v7c09bb
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = vec8411;
 assign w1 = vfc0c62;
 assign w2 = vd1c1a8;
 assign ve0793c = w3;
 assign v86c7f4 = w4;
 assign v8a6138 = w5;
 assign v7c09bb = w6;
 vf4ae9c_vee177d vee177d (
  .reset(w0),
  .clk(w1),
  .InPPM(w2),
  .Ch1(w3),
  .Ch2(w4),
  .Ch3(w5),
  .Ch4(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Deco_PPM_4  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Decodificador PPM 4 bits
/*-------------------------------------------------*/

module vf4ae9c_vee177d (
 input InPPM,
 input reset,
 input clk,
 output Ch1,
 output Ch2,
 output Ch3,
 output Ch4
);
 
 parameter [2:0] S0=0,S1=1,S2=2,S3=3,S4=4;
 
 reg Ch1=0,Ch2=0,Ch3=0,Ch4=0;
 
 reg [2:0]  estadoActual=0, estadoNext=0;
 
 // bloque secuencial. Capturar estado Actual
 always @(posedge clk or posedge reset)
 if(reset) estadoActual <= S0;
 else estadoActual <= estadoNext;
 
 // Bloque combinacional. Calculamos estado siguiente y valor de las
 // salidas en función de las entradas y del estado.
 always @(*)  // * para todas
 begin
   //valores por defecto
   Ch1   = 0;
   Ch2   = 0;
   Ch3   = 0;
   Ch4   = 0;
   estadoNext   = 'bx; //Depuración
   
   case(estadoActual)
      S0:begin                                   
         if(InPPM) begin   estadoNext = S1;   Ch1 <= 1'b1;   end 
         else              estadoNext = S0;
         end
      S1:begin                                   
         if(InPPM) begin   estadoNext = S2;   Ch2 <= 1'b1;   end 
         else      begin   estadoNext = S1;   Ch1 <= 1'b1;   end
         end
      S2:begin                                   
         if(InPPM) begin   estadoNext = S3;   Ch3 <= 1'b1;   end 
         else      begin   estadoNext = S2;   Ch2 <= 1'b1;   end
         end
      S3:begin                                   
         if(InPPM) begin   estadoNext = S4;   Ch4 <= 1'b1;   end 
         else      begin   estadoNext = S3;   Ch3 <= 1'b1;   end
         end
      S4:begin                                   
         if(InPPM)         estadoNext = S0;
         else      begin   estadoNext = S4;   Ch4 <= 1'b1;  end
         end
     
      default:             estadoNext = S0;
    endcase
 end
endmodule
//---- Top entity
module v21cfcc (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v21cfcc_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 0
/*-------------------------------------------------*/

module v21cfcc_vb2eccd (
 output q
);
 //-- Bit constante a 0
 assign q = 1'b0;
 
 
endmodule
