// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input ve61673,
 input vdd729a,
 output v66c37a,
 output vc3d1fa,
 output v10be74,
 output v0b79d7,
 output [0:7] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign w0 = vdd729a;
 assign w1 = ve61673;
 assign v0b79d7 = w2;
 assign v66c37a = w3;
 assign vc3d1fa = w4;
 assign v10be74 = w5;
 main_vbd6086 vbd6086 (
  .clk(w0),
  .rst(w1),
  .ov(w2),
  .q15(w3),
  .q14(w4),
  .q13(w5)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*-- Overflow_4ms  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Contador Reset y overflow a los 4ms
/*-------------------------------------------------*/

module main_vbd6086 (
 input rst,
 input clk,
 output q15,
 output q14,
 output q13,
 output ov
);
 
 reg [15:0] qi = 0;
 
 always @(posedge clk)
 begin
   if (rst | ov)
     qi <= 0;
   else 
       qi <= qi + 1; 
 end 
 
 //-- Comprobar overflow
 assign ov = (qi == 48000); //4ms
 assign q15 = qi[15];
 assign q14 = qi[14];
 assign q13 = qi[13];
endmodule
