// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input [3:0] vb702f1,
 input [3:0] v170aba,
 input v899cd3,
 output [3:0] ve042a7,
 output vbb1b85,
 output [0:7] vinit
);
 wire [0:3] w0;
 wire w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire w4;
 assign ve042a7 = w0;
 assign vbb1b85 = w1;
 assign w2 = vb702f1;
 assign w3 = v170aba;
 assign w4 = v899cd3;
 main_v11e293 v11e293 (
  .suma(w0),
  .Cout(w1),
  .a(w2),
  .b(w3),
  .Cin(w4)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*-- A+B  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- suma de dos números de 4 bits y acarreo
/*-------------------------------------------------*/

module main_v11e293 (
 input [3:0] a,
 input [3:0] b,
 input Cin,
 output [3:0] suma,
 output Cout
);
 
 reg  [4:0]  s;
 reg [3:0]   suma;
 reg         Cout;   
 
 always @(*)
 begin
   s = a + b + Cin; //suma con acarreo
   {suma,Cout} = {s[3:0],s[4]};
 end
 
endmodule
