// Code generated by Icestudio 0.7.1w202108130708

`default_nettype none

//---- Top entity
module main (
 input veaafb6,
 output v038f95,
 output vcaba90,
 output [0:6] vinit
);
 wire w0;
 wire w1;
 assign w0 = veaafb6;
 assign v038f95 = w0;
 assign w1 = veaafb6;
 assign vcaba90 = w1;
 assign w1 = w0;
 assign vinit = 7'b0000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
