// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input v6817fd,
 input vf3d207,
 input vc7d589,
 input v44d439,
 output v3f8381,
 output v1169dd,
 output [0:7] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign v3f8381 = w0;
 assign v1169dd = w1;
 assign w2 = v6817fd;
 assign w3 = vf3d207;
 assign w4 = vc7d589;
 assign w5 = v44d439;
 main_vd538b6 vd538b6 (
  .O1(w0),
  .O2(w1),
  .A(w2),
  .B(w3),
  .reset(w4),
  .clk(w5)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*-- Moore Verilog  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Ejemplo de una máquina de estados tipo Moore
/*-------------------------------------------------*/

module main_vd538b6 (
 input A,
 input B,
 input reset,
 input clk,
 output O1,
 output O2
);
 
 
 //@include 01_moore.v
 
 my_moore1  miMaquina(.clk(clk),.reset(reset),.inA(A),.inB(B),.OutA(O1),.OutB(O2));
endmodule
