// Code generated by Icestudio 0.7.1w202109100309
// Thu, 30 Sep 2021 19:35:54 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns          // 1 unidad de tiempo serán 10ns con una resolución de 1ns


module main_tb              
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;                    
 
 // Input/Output
 reg in;
 wire out;
 
 // Module instance
 main MAIN (
  .va3087a(in),
  .ve4bcac(out)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  in = 0;                                //Añado estas 3 lineas ****
  
  #10  in=1;    //a los 10 ciclos de reloj ( 10*10ns=100ns) in lo pongo a 1
  #10  in=0;    // a los 10 ciclos de reloj ( 10*10ns=100ns) in lo pongo a 0
  #3   in=1;    // a los 3 ciclos de reloj ( 10*10ns=100ns) in lo pongo a 1
  
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
