// Code generated by Icestudio 0.7.1w202108130708
// Thu, 09 Sep 2021 00:00:59 GMT

`default_nettype none

//---- Top entity
module main (
 input v9ed741,
 input vf842b6,
 output ve3259a,
 output [0:6] vinit
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v9ed741;
 assign w1 = vf842b6;
 assign ve3259a = w2;
 main_v0d0a4b v0d0a4b (
  .a(w0),
  .b(w1),
  .c(w2)
 );
 assign vinit = 7'b0000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v0d0a4b (
 input a,
 input b,
 output c
);
 assign c = a & b;
 
endmodule
