// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input vclk,
 output [0:7] vinit
);
 wire w0;
 assign w0 = vclk;
 main_vafeddf vafeddf (
  .clk(w0)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_vafeddf (
 input PPM_inv,
 input clk,
 output Ch1,
 output Ch2,
 output Ch3,
 output Ch4,
 output Ch5,
 output Ch6,
 output Ch7,
 output Ch8
);
 
 //@include Module_Decoder_8bits_ASIC_.v
 
 ppm8Ch MiPPM_8(.v35fe10(PPM_inv), .v357ff7(clk),
                .v980ce1(Ch1), .v5ad277(Ch2), .v9c8ff5(Ch3),
                .v755ffa(Ch4), .v9653af(Ch5), .vc74257(Ch6),
                .vd84530(Ch7), .va741a7(Ch8));
                
endmodule
