// Code generated by Icestudio 0.7.1w202108130708
// Thu, 16 Sep 2021 21:40:09 GMT

`default_nettype none

//---- Top entity
module main (
 output [0:7] vinit
);
 veebee1 v680557 (
 
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module veebee1 (
 input [1:0] vc9d156,
 input [1:0] v340b68,
 input v50d6c6,
 output [1:0] v7fb9b3
);
 wire w0;
 wire [0:1] w1;
 wire [0:1] w2;
 wire [0:1] w3;
 assign w0 = v50d6c6;
 assign v7fb9b3 = w1;
 assign w2 = vc9d156;
 assign w3 = v340b68;
 veebee1_ve4e0df ve4e0df (
  .sel(w0),
  .o(w1),
  .i1(w2),
  .i0(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 2 a 1 de 2 bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 2 a 1 de 2 bits
/*-------------------------------------------------*/

module veebee1_ve4e0df (
 input [1:0] i1,
 input [1:0] i0,
 input sel,
 output [1:0] o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 2 bits
 
 reg [1:0] o;
 
 always @(*) begin
     case(sel)
         0: o = i0;
         1: o = i1;
         default: o = i0;
     endcase
 end
 
 
endmodule
