// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input v8824f2,
 input v35fe10,
 input v71ba95,
 input v357ff7,
 output v980ce1,
 output v5ad277,
 output v9c8ff5,
 output v755ffa,
 output [0:7] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 assign w0 = v8824f2;
 assign w1 = v35fe10;
 assign w2 = v357ff7;
 assign v980ce1 = w3;
 assign v755ffa = w4;
 assign v5ad277 = w5;
 assign v9c8ff5 = w6;
 assign w12 = v357ff7;
 assign w14 = v71ba95;
 assign w15 = v357ff7;
 assign w16 = v357ff7;
 assign w19 = v357ff7;
 assign w10 = w8;
 assign w11 = w7;
 assign w12 = w2;
 assign w15 = w2;
 assign w15 = w12;
 assign w16 = w2;
 assign w16 = w12;
 assign w16 = w15;
 assign w19 = w2;
 assign w19 = w12;
 assign w19 = w15;
 assign w19 = w16;
 v3bfe20 vead016 (
  .ve7f5e6(w0),
  .v3c12b5(w7),
  .v717e81(w15)
 );
 v3bfe20 vdbde06 (
  .ve7f5e6(w1),
  .v717e81(w2),
  .v3c12b5(w8)
 );
 v816138 v7604a7 (
  .v3ca442(w9),
  .v0e28cb(w11),
  .vcbab45(w17)
 );
 v35f267 vd67e66 (
  .vcbab45(w9),
  .v0e28cb(w10)
 );
 v816138 v3ebf64 (
  .vcbab45(w13),
  .v0e28cb(w14),
  .v3ca442(w20)
 );
 veba410 v9b4ca7 (
  .vdd729a(w16),
  .ve61673(w17),
  .v0b79d7(w18)
 );
 v7a9412 v3be659 (
  .ve0793c(w3),
  .v7c09bb(w4),
  .v86c7f4(w5),
  .v8a6138(w6),
  .vd1c1a8(w7),
  .v381569(w8),
  .vfc0c62(w12),
  .vec8411(w13)
 );
 v3bfe20 v727d70 (
  .ve7f5e6(w18),
  .v717e81(w19),
  .v3c12b5(w20)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*-- Dec_PPMx4  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Decodificador 4 canales PPM
/*-------------------------------------------------*/
//---- Top entity
module v3bfe20 (
 input v717e81,
 input ve7f5e6,
 output v3c12b5
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = ve7f5e6;
 assign w1 = v717e81;
 assign v3c12b5 = w2;
 v3bfe20_v683a9f v683a9f (
  .i(w0),
  .clk(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Sync  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sincronizar las entradas de datos con el reloj del sistema
/*-------------------------------------------------*/

module v3bfe20_v683a9f (
 input clk,
 input i,
 output o
);
 // Sincronizacion. Evitar 
 // problema de la metaestabilidad
 
 reg d1;
 reg d2;
 
 always @(posedge clk)
  d1 <= i;
  
 always @(posedge clk)
   d2 <= d1;
   
 assign o = d2;
endmodule
//---- Top entity
module v816138 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v816138_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta OR
/*-------------------------------------------------*/

module v816138_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta OR
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a | b;
 
 //-- endmodule
endmodule
//---- Top entity
module v35f267 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v35f267_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT
/*-------------------------------------------------*/

module v35f267_vd54ca1 (
 input a,
 output c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
//---- Top entity
module veba410 (
 input ve61673,
 input vdd729a,
 output v0b79d7
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = vdd729a;
 assign w1 = ve61673;
 assign v0b79d7 = w2;
 veba410_vbd6086 vbd6086 (
  .clk(w0),
  .rst(w1),
  .ov(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Overflow_4ms  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Contador Reset y overflow a los 4ms
/*-------------------------------------------------*/

module veba410_vbd6086 (
 input rst,
 input clk,
 output ov
);
 
 reg [15:0] qi = 0;
 
 always @(posedge clk)
   if (rst | ov)  qi <= 0;
   else           qi <= qi + 1;
       
 //-- Comprobar overflow
 assign ov = (qi == 48000 );
     
endmodule
//---- Top entity
module v7a9412 (
 input vd1c1a8,
 input v381569,
 input vec8411,
 input vfc0c62,
 output ve0793c,
 output v86c7f4,
 output v8a6138,
 output v7c09bb
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign w0 = vec8411;
 assign w1 = vfc0c62;
 assign w2 = vd1c1a8;
 assign ve0793c = w3;
 assign v86c7f4 = w4;
 assign v8a6138 = w5;
 assign v7c09bb = w6;
 assign w7 = v381569;
 v7a9412_vee177d vee177d (
  .reset(w0),
  .clk(w1),
  .InPPM(w2),
  .Ch1(w3),
  .Ch2(w4),
  .Ch3(w5),
  .Ch4(w6),
  .InPPM_neg(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- Deco_PPM_4  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Decodificador PPM 4 bits
/*-------------------------------------------------*/

module v7a9412_vee177d (
 input InPPM,
 input InPPM_neg,
 input reset,
 input clk,
 output Ch1,
 output Ch2,
 output Ch3,
 output Ch4
);
 
 parameter [2:0] S0=0,S1=1,S2=2,S3=3,S4=4;
 
 reg Ch1=0,Ch2=0,Ch3=0,Ch4=0;
 
 reg [2:0]  estadoActual=0, estadoNext=0;
 
 // bloque secuencial. Capturar estado Actual
 
 always @(posedge clk )
 if(reset) estadoActual <= S0; 
 else estadoActual <= estadoNext;
 
 // Bloque combinacional. Calculamos estado siguiente y valor de las
 // salidas en función de las entradas y del estado actual.
 always @(InPPM or InPPM_neg or estadoActual)  // * para todas
 begin
   //valores por defecto
   Ch1   = 0;
   Ch2   = 0;
   Ch3   = 0;
   Ch4   = 0;
   estadoNext   = S0; 
   
   case(estadoActual)
      S0:begin                                   
         if(InPPM || !InPPM_neg  )  begin   estadoNext = S1;   Ch1 = 1'b1;   end 
         else                               estadoNext = S0;
         end
      S1:begin                                   
         if(InPPM || !InPPM_neg  )  begin   estadoNext = S2;   Ch2 = 1'b1;   end 
         else                       begin   estadoNext = S1;   Ch1 = 1'b1;   end
         end
      S2:begin                                   
         if(InPPM || !InPPM_neg  )  begin   estadoNext = S3;   Ch3 = 1'b1;   end 
         else                       begin   estadoNext = S2;   Ch2 = 1'b1;   end
         end
      S3:begin                                   
         if(InPPM || !InPPM_neg  )  begin   estadoNext = S4;   Ch4 = 1'b1;   end 
         else                       begin   estadoNext = S3;   Ch3 = 1'b1;   end
         end
      S4:begin                                   
         if(InPPM || !InPPM_neg  )          estadoNext = S0;
         else                       begin   estadoNext = S4;   Ch4 = 1'b1;  end
         end
     
      default:             estadoNext = S0;
    endcase
 end
endmodule
