// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input vclk,
 output v1fa947,
 output v02ba24,
 output [0:7] vinit
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire w4;
 wire w5;
 wire w6;
 assign v1fa947 = w4;
 assign v02ba24 = w5;
 assign w6 = vclk;
 main_v71a709 v71a709 (
  .CH1(w0),
  .CH2(w1),
  .CH3(w2),
  .CH4(w3),
  .PPM(w4),
  .PPM_I(w5),
  .clk(w6)
 );
 main_v390f47 v390f47 (
  .ch1(w0),
  .ch2(w1),
  .ch3(w2),
  .ch4(w3)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v71a709 (
 input [7:0] CH1,
 input [7:0] CH2,
 input [7:0] CH3,
 input [7:0] CH4,
 input clk,
 output PPM,
 output PPM_I
);
 
 parameter a = 12048;
 reg [18:0] canal1, canal2, canal3, canal4;
 reg PPM, PPM_I;
 reg [18:0] contador;
 
 always @(posedge clk)
 begin
   canal1 <= a + (CH1*47);
   canal2 <= a + (CH2*47);
   canal3 <= a + (CH3*47);
   canal4 <= a + (CH4*47);
 
 end
 
 always @(posedge clk)
 begin
   contador <= contador +1;
   if(contador == 1) PPM <= 1'b1;
   
 
 end
endmodule

module main_v390f47 (
 output [7:0] ch1,
 output [7:0] ch2,
 output [7:0] ch3,
 output [7:0] ch4
);
 
 assign ch1 = 128;
 assign ch2 = 128;
 assign ch3 = 128;
 assign ch4 = 128;
endmodule
