// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 output [7:0] v846c58,
 output [0:7] vinit
);
 wire [0:7] w0;
 assign v846c58 = w0;
 main_v28c694 v28c694 (
  .n(w0)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*-- Num = 85  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- paso de valor constante por parámetro
/*-------------------------------------------------*/

module main_v28c694 (
 output [7:0] n
);
 
 //module constante(output [7:0] n);
    
    localparam [7:0] numero = 8'b0101_0101;
     
 
      assign n = numero;
   
 // endmodule
 
endmodule
