// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input [7:0] v671660,
 input v4d1000,
 output [8:0] v286a72,
 output [0:7] vinit
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:8] w3;
 wire w4;
 assign w1 = v671660;
 assign w2 = v671660;
 assign v286a72 = w3;
 assign w4 = v4d1000;
 assign w2 = w1;
 v0fa131 v422d80 (
  .vb1059b(w0),
  .vec4656(w1),
  .v97b64a(w4)
 );
 vd25c5b v90b8a3 (
  .v2e2367(w0),
  .v77baa4(w2),
  .v91d3e1(w3)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*-- Paso Bajo  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Filtro paso bajo digital mas básico
/*-------------------------------------------------*/
//---- Top entity
module v0fa131 (
 input [7:0] vec4656,
 input v97b64a,
 output [7:0] vb1059b
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = v97b64a;
 assign w1 = vec4656;
 assign vb1059b = w2;
 v0fa131_v67385c v67385c (
  .clk(w0),
  .d(w1),
  .q(w2)
 );
endmodule

/*-------------------------------------------------*/
/*--  Z^-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Register using 8 bits as Input
/*-------------------------------------------------*/

module v0fa131_v67385c (
 input [7:0] d,
 input clk,
 output [7:0] q
);
 
 reg q=0;
 
 always @(posedge clk)
  q<=d;
 
 
 
 
 
endmodule
//---- Top entity
module vd25c5b (
 input [7:0] v77baa4,
 input [7:0] v2e2367,
 output [8:0] v91d3e1
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:8] w2;
 assign w0 = v77baa4;
 assign w1 = v2e2367;
 assign v91d3e1 = w2;
 vd25c5b_v957cbb v957cbb (
  .a(w0),
  .b(w1),
  .s(w2)
 );
endmodule

/*-------------------------------------------------*/
/*--  A + B  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Suma de 8 bits > 9 bits
/*-------------------------------------------------*/

module vd25c5b_v957cbb (
 input [7:0] a,
 input [7:0] b,
 output [8:0] s
);
 // suma
 assign s = a + b;
 
endmodule
