// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input [4:0] vbba179,
 input [4:0] v6923d5,
 output [7:0] v6d296e,
 output [0:7] vinit
);
 wire [0:4] w0;
 wire [0:4] w1;
 wire [0:7] w2;
 assign w0 = vbba179;
 assign w1 = v6923d5;
 assign v6d296e = w2;
 main_v11e293 v11e293 (
  .a(w0),
  .b(w1),
  .suma(w2)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*-- A+B  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- suma de dos números de 4 bits y acarreo
/*-------------------------------------------------*/

module main_v11e293 (
 input [4:0] a,
 input [4:0] b,
 output [7:0] suma
);
 
 wire signed [4:0] a,b;    //indico q son con signo
 wire signed  [7:0] suma;
 
 
 assign suma = a+b;
endmodule
