// Code generated by Icestudio 0.7.1w202108130708

`default_nettype none

//---- Top entity
module main #(
 parameter v6e44cd = -3
) (
 output [7:0] v1935a2
);
 localparam p1 = v6e44cd;
 wire [0:7] w0;
 assign v1935a2 = w0;
 v4e78df #(
  .v7b5247(p1)
 ) v805693 (
  .v9f8126(w0)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v4e78df #(
 parameter v7b5247 = 0
) (
 output [7:0] v9f8126
);
 localparam p0 = v7b5247;
 wire [0:7] w1;
 assign v9f8126 = w1;
 v4e78df_vea9bd0 #(
  .num(p0)
 ) vea9bd0 (
  .out(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Introducción de un valor constante global
/*-------------------------------------------------*/

module v4e78df_vea9bd0 #(
 parameter num = 0
) (
 output [7:0] out
);
 
 assign out = num ;
endmodule
