// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input v5f7ed1,
 input v3818e4,
 output v6f201c,
 output [0:6] vinit
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v5f7ed1;
 assign w1 = v3818e4;
 assign v6f201c = w2;
 main_v717b52 v717b52 (
  .A(w0),
  .B(w1),
  .O(w2)
 );
 assign vinit = 7'b0000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v717b52 (
 input A,
 input B,
 output O
);
 //@include And.v
 
 AndTop MiAnd(.vc2395b(A),.vb6b1a1(B),.v3ff3ed(O));
 
endmodule
