// Code generated by Icestudio 0.7.1w202108130708

`default_nettype none

//---- Top entity
module main (
 output [7:0] v776aaa
);
 wire [0:7] w0;
 assign v776aaa = w0;
 v2f2197 vbfa462 (
  .v701fbe(w0)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v2f2197 (
 output [7:0] v701fbe
);
 wire [0:7] w0;
 assign v701fbe = w0;
 v2f2197_v03f633 v03f633 (
  .out(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Hex_33  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 33 en hexadecimal
/*-------------------------------------------------*/

module v2f2197_v03f633 (
 output [7:0] out
);
 
 assign out =8'h33;
endmodule
