// Code generated by Icestudio 0.7.1w202109100309
// Wed, 08 Dec 2021 21:40:34 GMT

`default_nettype none

//---- Top entity
module main (
 input [11:0] vfde675,
 input [5:0] v372f3b,
 input v0781ab,
 input v34ab9c,
 input v62424b,
 input v94ba2d,
 input vc26473,
 output v3ac526,
 output vfa918b,
 output va1cf6d,
 output [2:0] v275b81,
 output v07eb9f,
 output v57f01e,
 output v633971,
 output v88aa7c,
 output v107387,
 output vd3f862,
 output v9d97c8,
 output v4a41d7
 
);
 wire [0:11] w0;
 wire [0:5] w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire [0:2] w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 assign w0 = vfde675;
 assign w1 = v372f3b;
 assign w2 = v0781ab;
 assign w3 = v62424b;
 assign w4 = v94ba2d;
 assign w5 = vc26473;
 assign v3ac526 = w6;
 assign vfa918b = w7;
 assign va1cf6d = w8;
 assign v275b81 = w9;
 assign v07eb9f = w10;
 assign v57f01e = w11;
 assign v633971 = w12;
 assign v107387 = w13;
 assign v88aa7c = w14;
 assign vd3f862 = w15;
 assign v9d97c8 = w16;
 assign v4a41d7 = w17;
 assign w18 = v34ab9c;
 assign w19 = v34ab9c;
 assign w19 = w18;
 main_v427507 v427507 (
  .ADC(w0),
  .config(w1),
  .resetA(w2),
  .PPM_out(w6),
  .PPM_Inv_out(w7),
  .Start(w8),
  .Selec(w9),
  .clk(w19)
 );
 main_vfdea0e vfdea0e (
  .PPM_in(w3),
  .PPM_Inv_in(w4),
  .resetB(w5),
  .Ch7(w10),
  .Ch6(w11),
  .Ch5(w12),
  .Ch4(w13),
  .Ch3(w14),
  .Ch2(w15),
  .Ch1(w16),
  .Ch0(w17),
  .clk(w18)
 );
 
endmodule

/*-------------------------------------------------*/
/*-- PPM Tx-Rx  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Modulo PPM Emisor-Receptor
/*-------------------------------------------------*/

module main_v427507 (
 input [11:0] ADC,
 input [5:0] config,
 input resetA,
 input clk,
 output PPM_out,
 output PPM_Inv_out,
 output Start,
 output [2:0] Selec
);
 // Codificador PPM
endmodule

module main_vfdea0e (
 input PPM_in,
 input PPM_Inv_in,
 input resetB,
 input clk,
 output Ch7,
 output Ch6,
 output Ch5,
 output Ch4,
 output Ch3,
 output Ch2,
 output Ch1,
 output Ch0
);
 //Decoder PPM
endmodule
