// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input v381569,
 input vec8411,
 input vfc0c62,
 output ve0793c,
 output v86c7f4,
 output v8a6138,
 output v7c09bb,
 output v1f42be,
 output vaf652b,
 output v3317f8,
 output v9c77dc,
 output [0:7] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 assign w0 = vec8411;
 assign w1 = vfc0c62;
 assign w2 = v381569;
 assign ve0793c = w3;
 assign v86c7f4 = w4;
 assign v8a6138 = w5;
 assign v7c09bb = w6;
 assign v1f42be = w7;
 assign vaf652b = w8;
 assign v3317f8 = w9;
 assign v9c77dc = w10;
 main_vee177d vee177d (
  .reset(w0),
  .clk(w1),
  .InPPM_neg(w2),
  .Ch1(w3),
  .Ch2(w4),
  .Ch3(w5),
  .Ch4(w6),
  .Ch5(w7),
  .Ch6(w8),
  .Ch7(w9),
  .Ch8(w10)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*-- Deco_PPM_4  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Decodificador PPM 4 bits
/*-------------------------------------------------*/

module main_vee177d (
 input InPPM_neg,
 input reset,
 input clk,
 output Ch1,
 output Ch2,
 output Ch3,
 output Ch4,
 output Ch5,
 output Ch6,
 output Ch7,
 output Ch8
);
 
 parameter [3:0] S0=0, S1=1, S2=2, S3=3, S4=4, S5=0, S6=0, S7=0, S8=0;              //Poner nombres a los estados
 
 reg Ch1=0, Ch2=0, Ch3=0, Ch4=0, Ch5=0, Ch6=0, Ch7=0, Ch8=0;                        //Inicializo canales
 
 reg [3:0]  estadoActual=0, estadoNext=0;                                           //Inicializo estados
 
 // bloque secuencial. Capturar estado Actual
 
 always @(posedge clk )
 if(reset) estadoActual <= S0; 
 else estadoActual <= estadoNext;
 
 // Bloque combinacional. Calculamos estado siguiente y valor de las
 // salidas en función de las entradas y del estado actual.
 
 always @(reset or InPPM_neg or estadoActual)  //  estado siguiente = función ( entradas y estado actual)
 begin
   //valores por defecto. justo antes del case pongo valores por defecto y en el case solo cambiamos
   //la salida que se ve afectada y las demás tomarán los valores por defecto
   Ch1   = 0;   Ch2   = 0;   Ch3   = 0;   Ch4   = 0; 
   Ch5   = 0;   Ch6   = 0;   Ch7   = 0;   Ch8   = 0;
   estadoNext   = S0; 
   
   case(estadoActual)  //Evaluación del estado actual
      S0:begin                                   
         if( InPPM_neg  )  begin   estadoNext = S1;   Ch1 = 1'b1;   end 
         else                      estadoNext = S0;  
         end
      S1:begin                                   
         if( InPPM_neg  )  begin   estadoNext = S2;   Ch2 = 1'b1;   end 
         else              begin   estadoNext = S1;   Ch1 = 1'b1;   end
         end
      S2:begin                                   
         if( InPPM_neg  )  begin   estadoNext = S3;   Ch3 = 1'b1;   end 
         else              begin   estadoNext = S2;   Ch2 = 1'b1;   end
         end
      S3:begin                                   
         if( InPPM_neg  )  begin   estadoNext = S4;   Ch4 = 1'b1;   end 
         else              begin   estadoNext = S3;   Ch3 = 1'b1;   end
         end
      S4:begin                                   
         if( InPPM_neg  )  begin   estadoNext = S4;   Ch5 = 1'b1;   end 
         else              begin   estadoNext = S3;   Ch4 = 1'b1;   end
         end
      S5:begin                                   
         if( InPPM_neg  )  begin   estadoNext = S4;   Ch6 = 1'b1;   end 
         else              begin   estadoNext = S3;   Ch5 = 1'b1;   end
         end
      S6:begin                                   
         if( InPPM_neg  )  begin   estadoNext = S4;   Ch7 = 1'b1;   end 
         else              begin   estadoNext = S3;   Ch6 = 1'b1;   end
         end
      S7:begin                                   
         if( InPPM_neg  )  begin   estadoNext = S4;   Ch8 = 1'b1;   end 
         else              begin   estadoNext = S3;   Ch7 = 1'b1;   end
         end
      S8:begin                                   
         if( InPPM_neg  )          estadoNext = S0;
         else              begin   estadoNext = S4;   Ch8 = 1'b1;  end
         end
      default:                     estadoNext = S0;
    endcase
 end
endmodule
