// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input v826ea3,
 input ve99f77,
 input v30e6b7,
 output v5faa99,
 output v1891e5,
 output [0:7] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v826ea3;
 assign w1 = ve99f77;
 assign w2 = v30e6b7;
 assign v5faa99 = w3;
 assign v1891e5 = w4;
 main_v9c7674 v9c7674 (
  .Start(w0),
  .reset(w1),
  .clk(w2),
  .Pulse_100us(w3),
  .Fin(w4)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v9c7674 (
 input Start,
 input reset,
 input clk,
 output Pulse_100us,
 output Fin
);
 // cuando llega un tic por Start
 // Se genera un pulso de 100 microsegundos
 // y al terminar se genera un tic de fin del pulso  por "Fin"
 
 parameter      S0=1'b0, S1=1'b1;   // 2 estados inicio y contando/comparando
 reg[10:0]      n=0;                // contador 11 bits hasta 2048, solo necesitamos
                                    // hasta 1200 conteos ( 100 us )
 reg Pulse_100us = 0, Fin = 0;
 reg estadoActual = 0, estadoSiguiente = 0;
 
 //bloque secuencial donde se asigna el estado Siguiente como el estado Actual ***************
 
 always @(posedge clk or posedge reset)
 begin
  if(reset)  estadoActual <= S0;
  else       estadoActual <= estadoSiguiente;
 end
 
 //bloque combinacional donde se calculan las salidas y los estados siguientes ***************
 
 always @(*)begin
 
 //valores por defecto que se aplican si no se indica nada en uno de los estados
 Pulse_100us = 0;
 Fin         = 0;
 n           = 0;
 
   case(estadoActual)
     S0:begin                   // Pulse_100us =0 Fin =0 n =0
          
        end
     S1:begin                   //Pulse_100us = 1 mientras esté en este estado
                                                         Pulse_100us = 1'b1; 
          if(n == 1200) begin   estadoSiguiente = S0;    Fin         = 1;     end  // Pulse_100us = 1  n = 0 Fin = 1 
          else          begin   estadoSiguiente = S1;    n           = n + 1; end  // Pulse_100us = 1  n=n+1 Fin = 0     
        end
     default:                   estadoSiguiente = S0;                              // Pulse_100us = 0  n = 0 Fin = 0
   endcase
 end
 
 
                              
 
endmodule
