// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input vdd4a98,
 input vclk,
 output [7:0] v465bb3
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire w3;
 assign v465bb3 = w0;
 assign w1 = vdd4a98;
 assign w3 = vclk;
 v35f267 vb19348 (
  .v0e28cb(w1),
  .vcbab45(w2)
 );
 main_va9029d va9029d (
  .d(w0),
  .rst_n(w2),
  .clk(w3)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v35f267 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v35f267_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT
/*-------------------------------------------------*/

module v35f267_vd54ca1 (
 input a,
 output c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule

module main_va9029d (
 input clk,
 input count,
 input rst_n,
 output [7:0] d
);
 
 
 reg [7:0] d=0;
 
 always@(posedge clk or negedge rst_n)
 begin
  if(!rst_n) 
    d<=0;
  else  
   if(count) 
       d<=d+1;
 end
 
 
endmodule
