// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input v961740,
 output [0:7] vinit
);
 wire w0;
 assign w0 = v961740;
 main_v922c36 v922c36 (
  .i(w0)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v922c36 (
 input i
);
 
 
 pullup pu(i);
endmodule
