// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main #(
 parameter v93f365 = 1
) (
 input vclk,
 output v1e9581,
 output v034022,
 output v3ce614,
 output [0:7] vinit
);
 localparam p5 = v93f365;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w6;
 wire w7;
 assign v3ce614 = w1;
 assign v1e9581 = w2;
 assign v034022 = w3;
 assign w6 = vclk;
 assign w7 = vclk;
 assign w7 = w6;
 v21cfcc vcc4531 (
  .v9fb85f(w0)
 );
 v561c34 vf48098 (
  .va0f1da(w0),
  .v2d5e76(w1),
  .v8a2f5b(w2),
  .v8b7d1f(w3),
  .vd33bc4(w4),
  .vbe9682(w6)
 );
 v519d31 #(
  .vfb06ae(p5)
 ) vcaea99 (
  .v2a8434(w4),
  .vac0eb2(w7)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v21cfcc (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v21cfcc_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 0
/*-------------------------------------------------*/

module v21cfcc_vb2eccd (
 output q
);
 //-- Bit constante a 0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module v561c34 (
 input vd33bc4,
 input va0f1da,
 input vbe9682,
 output v8a2f5b,
 output v8b7d1f,
 output v2d5e76
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire [0:11] w8;
 wire w9;
 wire w10;
 assign v2d5e76 = w2;
 assign w3 = vd33bc4;
 assign w4 = va0f1da;
 assign w5 = vbe9682;
 assign w6 = vbe9682;
 assign v8b7d1f = w7;
 assign v8a2f5b = w9;
 assign w6 = w5;
 assign w10 = w9;
 v35f267 vd274ba (
  .vcbab45(w7),
  .v0e28cb(w10)
 );
 v527849 v1a1ee6 (
  .v678d18(w0),
  .v2e69c1(w1),
  .v1891e5(w2),
  .v826ea3(w3),
  .ve99f77(w4),
  .v30e6b7(w6),
  .v38e151(w8),
  .v5faa99(w9)
 );
 v8e84fc vea661c (
  .v7c533e(w0),
  .ve61673(w1),
  .vdd729a(w5),
  .v8858b4(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- Pulse300us  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Crea un pulso de 100us al recibir un pulso por Start y manda un tic de fin al acabar el pulso de 100us
/*-------------------------------------------------*/
//---- Top entity
module v35f267 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v35f267_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT
/*-------------------------------------------------*/

module v35f267_vd54ca1 (
 input a,
 output c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
//---- Top entity
module v527849 (
 input [11:0] v38e151,
 input v826ea3,
 input ve99f77,
 input v30e6b7,
 output v5faa99,
 output v2e69c1,
 output v678d18,
 output v1891e5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire [0:11] w7;
 assign w0 = v826ea3;
 assign w1 = ve99f77;
 assign w2 = v30e6b7;
 assign v1891e5 = w3;
 assign v2e69c1 = w4;
 assign v678d18 = w5;
 assign v5faa99 = w6;
 assign w7 = v38e151;
 v527849_v9c7674 v9c7674 (
  .Start(w0),
  .reset(w1),
  .clk(w2),
  .Fin(w3),
  .reset_n(w4),
  .inc_n(w5),
  .Pulse_300us(w6),
  .n(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- Maquina300us  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module v527849_v9c7674 (
 input [11:0] n,
 input Start,
 input reset,
 input clk,
 output Pulse_300us,
 output reset_n,
 output inc_n,
 output Fin
);
 // cuando llega un tic por Start
 // Se genera un pulso de 300 microsegundos
 // y al terminar se genera un tic de fin del pulso  por "Fin"
 
 parameter      S0=1'b0, S1=1'b1;   // 2 estados inicio y contando/comparando
                                    // hasta 3600 conteos ( 300 us )
                                    
 reg Pulse_300us = 0, reset_n =0, inc_n =0, Fin = 0;
 reg estadoActual = 0, estadoSiguiente = 0;
 
 //bloque secuencial donde se asigna el estado Siguiente como el estado Actual ***************
 
 always @(posedge clk or posedge reset)
 begin
  if(reset)  estadoActual <= S0;
  else       estadoActual <= estadoSiguiente;
 end
 
 //bloque combinacional donde se calculan las salidas y los estados siguientes ***************
 
 always @(*)begin
 
 //valores por defecto que se aplican si no se indica nada en uno de los estados
 Pulse_300us = 0;
 reset_n     = 0;
 inc_n       = 0;
 Fin         = 0;
 
   case(estadoActual)
     S0:begin                   
          if(Start)             estadoSiguiente = S1;
          else                  estadoSiguiente = S0;
        end
     S1:begin                   //Pulse_100us = 1 mientras esté en este estado
                                                         Pulse_300us = 1'b1; 
          if(n == 3600) begin   estadoSiguiente = S0;    Fin         = 1;  reset_n = 1;    end  // Pulse_300us = 1  n = 0 Fin = 1 
          else          begin   estadoSiguiente = S1;    inc_n = 1;                        end  // Pulse_300us = 1  n=n+1 Fin = 0     
        end
     default:                   estadoSiguiente = S0;                              // Pulse_300us = 0  n = 0 Fin = 0
   endcase
 end
 
 
                              
 
endmodule
//---- Top entity
module v8e84fc #(
 parameter v5e4a03 = 4096
) (
 input vdd729a,
 input ve61673,
 input v7c533e,
 output [11:0] v8858b4,
 output v712cd1
);
 localparam p1 = v5e4a03;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire [0:11] w5;
 assign w0 = ve61673;
 assign w2 = v7c533e;
 assign w3 = vdd729a;
 assign v712cd1 = w4;
 assign v8858b4 = w5;
 v8e84fc_vbd6086 #(
  .M(p1)
 ) vbd6086 (
  .rst(w0),
  .cnt(w2),
  .clk(w3),
  .ov(w4),
  .q(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Contador-12bits-up-rst  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Contador módulo M, ascendente, de 12 bits, con reset 
/*-------------------------------------------------*/

module v8e84fc_vbd6086 #(
 parameter M = 0
) (
 input clk,
 input rst,
 input cnt,
 output [11:0] q,
 output ov
);
 //-- Numero de bits del contador
 localparam N = 12; 
 
 //-- En contadores de N bits:
 //-- M = 2 ** N
 
 //-- Internamente usamos un bit mas
 //-- (N+1) bits
 reg [N:0] qi = 0;
 
 always @(posedge clk)
   if (rst | ov)
     qi <= 0;
   else
     if (cnt)
       qi <= qi + 1;
       
 assign q = qi;
 
 //-- Comprobar overflow
 assign ov = (qi == M);
     
endmodule
//---- Top entity
module v519d31 #(
 parameter vfb06ae = 100
) (
 input vac0eb2,
 output v2a8434
);
 localparam p2 = vfb06ae;
 wire w0;
 wire w1;
 assign v2a8434 = w0;
 assign w1 = vac0eb2;
 v519d31_v6cac2f #(
  .MS(p2)
 ) v6cac2f (
  .o(w0),
  .clk(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Corazon-tic-ms  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Corazón de bombeo de tics a con periodo paramétrico de milisegundos
/*-------------------------------------------------*/

module v519d31_v6cac2f #(
 parameter MS = 0
) (
 input clk,
 output o
);
 //localparam MS;
 
 //-- Constante para dividir y obtener una frecuencia de 1KHz
 localparam M = 12000*MS;
 
 //-- Calcular el numero de bits para almacenar M
 localparam N = $clog2(M);
 
 //-- Cable de reset para el contador
 wire reset;
 
 //-- Registro del divisor
 reg [N-1:0] divcounter;
 
 
 //-- Contador con reset
 always @(posedge clk)
   if (reset)
     divcounter <= 0;
   else
     divcounter <= divcounter + 1;
 
 //-- Comparador que resetea el contador cuando se alcanza el tope
 assign reset = (divcounter == M-1);
 
 //-- La salida es la señal de overflow
 assign o = reset;
 
 
 
 
endmodule
