// Code generated by Icestudio 0.7.1w202108130708

`default_nettype none

//---- Top entity
module main (
 output v3886f0,
 output [0:6] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign v3886f0 = w4;
 assign w1 = w0;
 assign w3 = w2;
 main_v62519f v62519f (
  .C(w0),
  .D(w1),
  .A(w2),
  .B(w3),
  .f(w4)
 );
 v21cfcc v1c0224 (
  .v9fb85f(w0)
 );
 v725b7e v0f72ed (
  .v9fb85f(w2)
 );
 assign vinit = 7'b0000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v21cfcc (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v21cfcc_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 0
/*-------------------------------------------------*/

module v21cfcc_vb2eccd (
 output q
);
 //-- Bit constante a 0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module v725b7e (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v725b7e_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 1
/*-------------------------------------------------*/

module v725b7e_vb2eccd (
 output q
);
 //-- Bit constante a 1
 assign q = 1'b1;
 
 
endmodule

module main_v62519f (
 input A,
 input B,
 input C,
 input D,
 output f
);
 //module uso_wire(A,B,C,D,f);
 //input A,B,C,D;
 //output f;
  wand f;
 
  assign f=(A & B);
  assign f=(C | D);
 //endmodule
 
endmodule
